apiVersion: v1
kind: Service
metadata:
  name: tawazun-service
  namespace: raghadalrehaili-tawazun
  labels:
    app: tawazun-app
    name: RaghadAlrehaili
spec:
  type: NodePort
  ports:
    - name: tawazun-service-port
      port: 80
      targetPort: 8080
      nodePort: 31000
      protocol: TCP
  selector:
    app: tawazun