apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-deployment
  namespace: raghadalrehaili-tawazun
  labels:
    app: mysql-db
    name: RaghadAlrehaili
spec:
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              value: "mysql"
            - name: MYSQL_DATABASE
              value: "mysql"
            - name: MYSQL_PASSWORD
              value: "mysql"
            - name: MYSQL_ROOT_PASSWORD
              value: "mysql"   
          livenessProbe: 
            tcpSocket:
              port: 3306
            initialDelaySeconds: 2  
            periodSeconds: 2 
            timeoutSeconds: 1 
            successThreshold: 1 
            failureThreshold: 3      
          volumeMounts:
            - mountPath: /mysqldb/volume/data
              name: mysqldb-volume
      volumes:  
        - name: mysqldb-volume
          persistentVolumeClaim:
            claimName: mysqldb-pvc
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db