apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-deployment
  namespace: raghadalrehaili-tawazun
  labels:
    app: mysql-db
    name: RaghadAlrehaili
spec:
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          resources: 
            requests: 
              memory: "260Mi"
              cpu: "220m"
            limits:
              memory: "550Mi"
              cpu: "550m"
          env:
            - name: MYSQL_USER
              value: "mysql"
            - name: MYSQL_DATABASE
              value: "mysql"
            - name: MYSQL_PASSWORD
              value: "mysql"
            - name: MYSQL_ROOT_PASSWORD
              value: "mysql"       
          volumeMounts:
            - mountPath: /mysqldb/volume/data
              name: mysqldb-volume
      volumes:  
        - name: mysqldb-volume
          persistentVolumeClaim:
            claimName: mysqldb-pvc
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db