apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqldb-pv
  namespace: raghadalrehaili-tawazun
  labels:
    app: mysqldb-vol
    type: local
    name: RaghadAlrehaili
spec:
  hostPath:
    path: "/mnt/volume/data"
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce