apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service
  namespace: raghadalrehaili-tawazun
  labels:
    app: mysqldb-svc
    name: RaghadAlrehaili
spec:
  type: ClusterIP
  ports:
    - name: mysqldb-service-port
      port: 3306
      targetPort: 3306
  selector:
    app: mysql-db