apiVersion: v1
kind: Service
metadata:
  name: tawazun-svc
  namespace: raghadalrehaili-tawazun
  labels: 
    name: name
spec:
  ports:
    - port: 80 
      targetPort: 8080
  type: LoadBalancer 
  selector:
    app: tawazun
