apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb-pvc
  namespace: raghadalrehaili-tawazun
  labels:
    app: mysqldb-pv-claim
    name: RaghadAlrehaili
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
  
